### ISSUE TITLE
[Codacy code cleanup] occurrence: 265 pattern: defined from star imports

### ISSUE THREAD

**Issue by rkothiya** [Seagate/cortx-motr#1823]
### Problem

We see 265 occurrence of pattern, "defined from star imports"

### Expected behavior

We should not be getting these warnings

### How to reproduce

```# find . -iname "*.py" -exec pyflakes {} \; | grep "defined from star imports" ```

### Deployment information

```# yum install python3-pyflakes.noarch```

**Comment by alfhad** [comment]
I would like to take this up.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31632. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by alfhad** [comment]
The following PR addresses this issue: 
https://github.com/Seagate/cortx-motr/pull/1828

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Following Test for fired to test this : 
 [https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/1288/#showFailuresLink]

Following 3 failures are seen :
 * [01motr-single-node.52motr-singlenode-sanity.test|https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/1288/testReport/junit/01motr-single-node/52motr-singlenode-sanity/test/]
 * [01motr-single-node.00userspace-tests.test|https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Motr/1288/testReport/junit/01motr-single-node/00userspace-tests/test/]
 * 03motr-single-node.71spiel-sns-motr-repair.test
|2 test failures are the usual know test failures. However *03motr-singe-node.71speil-sns-motr-repair.test* is new and now seen in the other test results which does not contain this patch.|

**Comment by rkothiya** [comment]
The corresponding pr is resolved by ignoring the warning, hence closing the issue.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

Since chronometry tools are no longer maintained in the motr repository, instead they are now shifted to the below repository but are kept in motr just because the other repository is still not open sourced, hence we have discussed and agreed to ignore the chronometry code from codacy. 
[https://github.com/Seagate/seagate-tools/tree/main/performance/PerfLine/roles/perfline_setup/files/chronometry]

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

As agreed we have ignored the chronometry files for codacy warnings.

**Comment by cortx-admin** [comment]
> Rinku Kothiya commented in Jira Server:

We no longer see these warnings in Codacy.
